version: "3.9"

services:
  # -----------------------------------------------------------
  # Postgres Database
  # -----------------------------------------------------------
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: keycloak
    ports:
      - "55432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default

  database_migrations:
    image: migrate/migrate:latest
    restart: on-failure
    volumes:
      - ./database-migrations/migrations:/migrations
    depends_on:
      - postgres
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "postgres://postgres:postgres@postgres:5432/keycloak?sslmode=disable",
        "up",
      ]
    networks:
      - default

  # -----------------------------------------------------------
  # Keycloak Authentication Server
  # -----------------------------------------------------------
  keycloak:
    image: quay.io/keycloak/keycloak:latest

    # Use the new "start-dev" command for Keycloak 17+ in dev mode
    command: >
      start-dev 
      --hostname-strict=false

    # Required environment variables
    environment:
      # Create admin user
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      # Database configuration (KC_ prefix)
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KC_DB_SCHEMA: keycloak

      # (Optional) Additional settings
      KC_HOSTNAME_STRICT: "false" # So you can access Keycloak from any hostname while in dev

    depends_on:
      - postgres
      - database_migrations

    ports:
      - "58080:8080" # Port for the Keycloak UI / REST
      # - "58443:8443" # If you configure SSL for dev (often omitted in dev mode)

    volumes:
      - keycloak_data:/opt/keycloak/data

    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  postgres_data:
  keycloak_data:
