version: '3.9'

services:

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - appointment-service
      - order-service
      - patient-service
      - record-service
      - lab-service
      - prescription-service
      - referral-service

  appointment-service:
    build: ./appointment-service
    ports: ["8081:8081"]

  order-service:
    build: ./order-service
    ports: ["8083:8083"]

  patient-service:
    build: ./patient-service
    ports: ["8082:8082"]

  record-service:
    build: ./record-service
    ports: ["8084:8084"]

  lab-service:
    build: ./lab-service
    ports: ["8085:8085"]

  prescription-service:
    build: ./prescription-service
    ports: ["8086:8086"]

  referral-service:
    build: ./referral-service
    ports: ["8087:8087"]
