version: "3.9"

services:
  # -----------------------------------------------------------
  # Postgres Database
  # -----------------------------------------------------------
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: keycloak
    ports:
      - "55432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - default

  database_migrations:
    image: migrate/migrate:latest
    restart: on-failure
    volumes:
      - ./database-migrations/migrations:/migrations
    depends_on:
      postgres:
        condition: service_healthy
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "postgres://postgres:postgres@postgres:5432/keycloak?sslmode=disable",
        "up",
      ]
    networks:
      - default

  # -----------------------------------------------------------
  # Keycloak Authentication Server
  # -----------------------------------------------------------
  keycloak:
    image: quay.io/keycloak/keycloak:latest

    # Use the new "start-dev" command for Keycloak 17+ in dev mode
    command: >
      start-dev 
      --hostname-strict=false

    # Required environment variables
    environment:
      # Create admin user
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      # Database configuration (KC_ prefix)
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KC_DB_SCHEMA: keycloak

      # (Optional) Additional settings
      KC_HOSTNAME_STRICT: "false" # So you can access Keycloak from any hostname while in dev

    depends_on:
      postgres:
        condition: service_healthy
      database_migrations:
        condition: service_completed_successfully

    ports:
      - "58080:8080" # Port for the Keycloak UI / REST
      # - "58443:8443" # If you configure SSL for dev (often omitted in dev mode)

    volumes:
      - keycloak_data:/opt/keycloak/data

    networks:
      - default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 5

  # -----------------------------------------------------------
  # Microservices
  # -----------------------------------------------------------
  auth-service:
    build:
      context: ./auth-service
      dockerfile: ./auth-service/Dockerfile
    restart: unless-stopped
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: keycloak
      KEYCLOAK_BASE_URL: http://keycloak:8080
      KEYCLOAK_REALM: fitnis
      KEYCLOAK_CLIENT_ID: auth-service
      PORT: 8080
    ports:
      - "8081:8080"
    depends_on:
      keycloak:
        condition: service_healthy
    networks:
      - default

  patient-service:
    build:
      context: ./patient-service
      dockerfile: ./patient-service/Dockerfile
    restart: unless-stopped
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: keycloak
      KEYCLOAK_BASE_URL: http://keycloak:8080
      KEYCLOAK_REALM: fitnis
      KEYCLOAK_CLIENT_ID: patient-service
      PORT: 8080
    ports:
      - "8082:8080"
    depends_on:
      keycloak:
        condition: service_healthy
    networks:
      - default

  appointment-service:
    build:
      context: ./appointment-service
      dockerfile: ./appointment-service/Dockerfile
    restart: unless-stopped
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: keycloak
      KEYCLOAK_BASE_URL: http://keycloak:8080
      KEYCLOAK_REALM: fitnis
      KEYCLOAK_CLIENT_ID: appointment-service
      PORT: 8080
    ports:
      - "8083:8080"
    depends_on:
      keycloak:
        condition: service_healthy
    networks:
      - default

  medical-records-service:
    build:
      context: ./medical-records-service
      dockerfile: ./medical-records-service/Dockerfile
    restart: unless-stopped
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: keycloak
      KEYCLOAK_BASE_URL: http://keycloak:8080
      KEYCLOAK_REALM: fitnis
      KEYCLOAK_CLIENT_ID: medical-records-service
      PORT: 8080
    ports:
      - "8084:8080"
    depends_on:
      keycloak:
        condition: service_healthy
    networks:
      - default

  laboratory-service:
    build:
      context: ./laboratory-service
      dockerfile: ./laboratory-service/Dockerfile
    restart: unless-stopped
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: keycloak
      KEYCLOAK_BASE_URL: http://keycloak:8080
      KEYCLOAK_REALM: fitnis
      KEYCLOAK_CLIENT_ID: laboratory-service
      PORT: 8080
    ports:
      - "8085:8080"
    depends_on:
      keycloak:
        condition: service_healthy
    networks:
      - default

  prescription-service:
    build:
      context: ./prescription-service
      dockerfile: ./prescription-service/Dockerfile
    restart: unless-stopped
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: keycloak
      KEYCLOAK_BASE_URL: http://keycloak:8080
      KEYCLOAK_REALM: fitnis
      KEYCLOAK_CLIENT_ID: prescription-service
      PORT: 8080
    ports:
      - "8086:8080"
    depends_on:
      keycloak:
        condition: service_healthy
    networks:
      - default

  referral-service:
    build:
      context: ./referral-service
      dockerfile: ./referral-service/Dockerfile
    restart: unless-stopped
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: keycloak
      KEYCLOAK_BASE_URL: http://keycloak:8080
      KEYCLOAK_REALM: fitnis
      KEYCLOAK_CLIENT_ID: referral-service
      PORT: 8080
    ports:
      - "8087:8080"
    depends_on:
      keycloak:
        condition: service_healthy
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  postgres_data:
  keycloak_data:
